version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: uivmp
      POSTGRES_PASSWORD: uivmp
      POSTGRES_DB: uivmp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  backend:
    build:
      context: ../
      dockerfile: infra/dockerfiles/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql+psycopg2://uivmp:uivmp@postgres:5432/uivmp
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4jpassword
      PLUGINS_DIR: /app/plugins
    depends_on:
      - postgres
      - neo4j
    ports:
      - "8000:8000"
    volumes:
      - ../plugins:/app/plugins:ro

  worker:
    build:
      context: ../
      dockerfile: infra/dockerfiles/Dockerfile.worker
    environment:
      DATABASE_URL: postgresql+psycopg2://uivmp:uivmp@postgres:5432/uivmp
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ../
      dockerfile: infra/dockerfiles/Dockerfile.frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data: {}
  neo4j-data: {}
